import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={clsx(raleway.className, 'max-w-full bg-ebony-950')}>
        <Navbar />
        <main className='text-white min-h-screen'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
